### PR TITLE
Update scripts to fetch and repackage helpshift 5.8.0

### PR DESCRIPTION
**Pull request by kenshin03**
Resolves https://github.com/Flipboard/Flipboard-iOS/issues/5275

This PR revisits the `FLFlipboard` project, which is an Xcode project with a few scripts that:
- Grabs the latest Helpshift SDK using cocoa pods
- Removes language files that aren't needed in Flipboard
- Replace some strings with our own version
- Re-package everything as a framework.

Since the last time this was updated (Feb 2016), Cocoapods has changed, Xcode has changed and the way Helpshift packages its language files has also changed. This PR makes the necessary updates here and there to ensure the process still works.

Please help to review @jeffweitzel. I'll update the wiki at https://flwiki.flipboard.com/display/AE/FLHelpshift once this and https://github.com/Flipboard/Flipboard-iOS/pull/5276 have been approved. Thanks.

### CODE REVIEW

**Comment by kenshin03** [comment]
Re-ran the script to update to Helpshift SDK 5.8.0.

**Comment by jeffweitzel** [comment]
Er, looks fine to me. If you doing all of this horribly wrong, it would probably still look fine. :shipit:

**Comment by kenshin03** [comment]
Thanks @jeffweitzel for reviewing! Yeah the only way to know this went well is for support to help test it out in beta and verify things weren't broken. 

Integrated to Flipboard-iOS project at https://github.com/Flipboard/Flipboard-iOS/pull/5276.

After I get an okay from support, I'll do a new release of `FLHelpshift` and then [update the cartfile](https://github.com/Flipboard/Flipboard-iOS/pull/5276/commits/17f7a7e9ea59f63ee705535f8ea19569eecdb6ac) to point to a version instead of a commit hash.

**Comment by kenshin03** [comment]
Merged to master at 97400ad.

**Pull request closed without merging**
